name: rad_mock_up
version: 1.0.0+1
publish_to: none
description: A mock up for rada egerton chapter
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.4
  flutter: 
    sdk: flutter
  getsocket: ^1.0.1
  socket_io_client: ^1.0.1
  image_picker: ^0.8.3+1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"  
flutter: 
  uses-material-design: true
  assets:
    - assets/chat.png
    - assets/icon_.png
    - assets/transparent.png
    - assets/icon_foreground.png
    - assets/bubble.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_.png"
  adaptive_icon_background: "assets/transparent.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

